### ISSUE TITLE
Clean canvas

### ISSUE THREAD

**Issue by orcunyavuz** [kevinstumpf/react-native-signature-pad#1]
Thanks for your efforts. Nice work indeed.

New to react native and couldn't find a way to clear signed canvas. How can we do it?

**Comment by kevinstumpf** [comment]
The simplest React Native-only approach would be to re-render a new instance of the Signature Pad when you want to clear it.

**Comment by CoderStav** [comment]
@kevinstumpf React Native novice here,  how would you re-render a new instance of the Signature Pad?

**Comment by AhmetSert** [comment]
Hi, @JimmyStavros 
I solved this issue with a simplest way. I used a state parameter and bind it a button like 'Clear'.

`{this.state.show ?
    <SignaturePad ref={'SignaturePad'}
                onError={this.signaturePadError}
                onChange={this.signaturePadChange}
                style={{ backgroundColor: 'white' }}/>
    :`null`
}`

In onPress() function of Clear button use this:

`onPress() {
this.setState({ show: false });
this.setState({ show: true });
}`

**Comment by patmisch** [comment]
The solution suggested by @AhmetSert doesn't seem to work for me. Has anyone figured out another way to clear the pad?

**Comment by kevinstumpf** [comment]
Can you post your code? Can you try, for the fun of it (haven't tried it myself):

``` js
onPress() { 
this.setState({ show: false }); 
setTimeout( () => { this.setState({ show: true }); }, 0);
}
```

If that also doesn't work for you -- can you set the timeout to something noticeable (say 5sec) and ensure that the signature pad actually disappears and reappears?

**Comment by patmisch** [comment]
Thanks! Wrapping it in setTimeout did the trick.
