### ISSUE TITLE
Signature resolution/clarity

### ISSUE THREAD

**Issue by kevinnguy** [kevinstumpf/react-native-signature-pad#11]
Is there a way to increase the resolution/clarity of the signature? Testing on both iOS and Android devices. Thanks for the great work @kevinstumpf !

**Comment by blaues0cke** [comment]
It seems there is no way to modify this from react right now. You may fork this repository and make line `36` and line `37` in `application.js` changeable:

```
signaturePad.minWidth = 1;
signaturePad.maxWidth = 4;
```

**Comment by kevinnguy** [comment]
Thanks @blaues0cke !
