### ISSUE TITLE
Signaturepad is not full screen

### ISSUE THREAD

**Issue by forki** [kevinstumpf/react-native-signature-pad#19]
We tried to put the signaturepa into a view but whatever we do we can't get it full screen:

![signature](https://cloud.githubusercontent.com/assets/57396/26355242/3486be4a-3fc8-11e7-96a4-7cd22a57d76c.png)

Even if the pad is the only control on the screen the display field is only that small rectangle

**Comment by daltondanis** [comment]
Two Questions:
1st. have you rotated the view to see if it's full screen?
2nd. have you tried different styles? (within a container view or etc..) provide a sample.

**Comment by forki** [comment]
What do you mean with rotate?

**Comment by daltondanis** [comment]
@forki landscape or portrait with the simulator or mobile device

**Comment by forki** [comment]
putting it into yet another view worked. thanks
