### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by mintotsai** [kevinstumpf/react-native-signature-pad#2]
I'm trying to rotate the signature pad on android so that I have some text at the top with the signature at the bottom.

Using transform rotation, the pad seems to disappear. What could I be doing wrong?

`<View style={{flex: 1}}>
        <Text>Consent Form</Text>
        <SignaturePad onError={this._signaturePadError}
                      onChange={this._signaturePadChange}
                      style={{ transform: [{rotate: '90deg'}] }}/>
      </View>`

Thanks for putting this together!

**Comment by kevinstumpf** [comment]
Hey,

In our case, we rotate the entire rendered scene/route. This is the style we're using:

``` js
const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;
const sceneWidth = deviceHeight;
const sceneHeight = deviceWidth;

var styles = StyleSheet.create({
  scene: {
    width: sceneWidth,
    height: sceneHeight,
    //We are first translating the canvas such that its center is at the top left corner
    //We then move it to the bottom right again to fill the entire viewport
    transform: [{translateX: -sceneWidth / 2}, {translateY: -sceneHeight / 2}, {rotate: '-90deg'},
      {translateX: -sceneWidth / 2}, {translateY: sceneHeight / 2}]
  }
});
```

Hope that helps

**Comment by mintotsai** [comment]
I'll give this a try. Thanks for the quick reply!

**Comment by srichallamalla935** [comment]
Tranform is not working in ios even my screen in not rotating..can someone help me


```
  <SignaturePad
              ref={'SignaturePad'}
              onError={this._signaturePadError}
              defaultWidth={width}
              defaultHeight={height}
              // onChange={this._signaturePadChange}
              style={{
                backgroundColor: 'white',

                  transform: [{rotate: '90deg'}],
              }}
            />
```
