### ISSUE TITLE
Done with Signature

### ISSUE THREAD

**Issue by eyalabadi98** [kevinstumpf/react-native-signature-pad#20]
Hello!

First of all, great work with this signature pad! 
I am wondering how we can make the component save the image when the user clicks on done. 

AKA, how did you get your example working with a done button and saving that image?

Thank you

**Comment by eyalabadi98** [comment]
Actually I figured it out. I implemented a queue, and then I pop it when i click done

**Comment by PManager1** [comment]
@eyalabadi98  how did you implemented that ?

**Comment by eyalabadi98** [comment]
@jpca999 Hey sorry, i created a queue or stack and whenever I click a button, it popped the last item

**Comment by cohendl** [comment]
@eyalabadi98 Could you explain how you turned the base64url into a png? Thanks!

**Comment by eyalabadi98** [comment]
Yeah.
I didnt turn a bsase64 into png, but rather I turned a base64 into an image straight in react native. I used:
`<Image 
source={{uri: this.props.games.team1Signature }} 
style={{ height: 100, width: 100 }}
/>}`
If you want to save image64 to png, use http://freeonlinetools24.com/base64-image

**Comment by cohendl** [comment]
I need to capture it and send it via REST API to Salesforce. But I need to send it as a .png instead of base64 string. How can I convert programmatically from base64 string -> .png before sending via API?

**Comment by eyalabadi98** [comment]
try this: https://stackoverflow.com/questions/16968945/convert-base64-png-data-to-javascript-file-objects

if it doesnt work, keep googling it

**Comment by cohendl** [comment]
Unfortunately it doesn't look like Blob, or anything similar, work with react native :/

**Comment by timt** [comment]
Not an issue with this library
