### ISSUE TITLE
how can i change the color of signature lines from black to blue ?

### ISSUE THREAD

**Issue by PManager1** [kevinstumpf/react-native-signature-pad#22]
![image](https://user-images.githubusercontent.com/1026325/28898792-c3404cf8-77b5-11e7-9039-cc88aa039e89.png)

**Comment by satishsynnov** [comment]
Hi @jpca999 try like this
var pencolor = "blue";
`<SignaturePad 
                            onError={this._signaturePadError}
                            onChange={this._signaturePadChange}
                            style={Styles.signPad} 
                            penColor={pencolor}
                          />`
