### ISSUE TITLE
Drawing outside of Range

### ISSUE THREAD

**Issue by eyalabadi98** [kevinstumpf/react-native-signature-pad#25]
Hello,

I am having some trouble limiting how a person can sign. If a person finishes drawing outside of the signature pad it doesnt recognize it as on done, and im having some problems.

I tried enclosing it in a view but no success.

Any advice?
Thank you

**Comment by yingdongzhang** [comment]
@eyalabadi98 

Might be a bit too late, I made a PR here which stops the signature from going outside of the canvas:

https://github.com/kevinstumpf/react-native-signature-pad/pull/34

if you can't wait for it to be merged, you can just fork it and change the file by yourself.

**Comment by yingdongzhang** [comment]
@eyalabadi98 

This might be a bit too late, but I made a PR which solves this issue: #34 

If you can wait for it to be merged, you can fork it and put the change in by yourself.

**Comment by timt** [comment]
#34 Merged and published
