### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.bool')

### ISSUE THREAD

**Issue by cohendl** [kevinstumpf/react-native-signature-pad#26]
Anyone else having this issue after upgrading to newest version of React?  I LOVE this component and would love to figure out how to get it up and running again! Thanks!!

**Comment by PManager1** [comment]
![image](https://user-images.githubusercontent.com/1026325/32694043-792e64d0-c704-11e7-9617-f26d557f5d84.png)

@kevinstumpf   any plan to update it to latest react version ?

**Comment by menderleit** [comment]
Same issue here...

**Comment by minhphung210** [comment]
same issues

**Comment by PManager1** [comment]
@EvanBacon   we got same issue over here too.

**Comment by EvanBacon** [comment]
@jpca999 any reason I was CC'd on this? I think someone just needs to put in a PR, but I would use PIXI in EXGL instead.

**Comment by PManager1** [comment]
I had a hunch that you'll know the solution to this issue and I was right..  thanks man.

**Comment by EvanBacon** [comment]
💙💙 I can put together something if that helps, PIXI in React Native is pretty new (Expo v24)

**Comment by PManager1** [comment]
@EvanBacon  that would be great.   I appreciate it man!

**Comment by EvanBacon** [comment]
@jpca999 here is an EXGL implementation of sketching: https://github.com/expo/expo-pixi/blob/edc107aefdd977fe5dd4997689c5270f23113068/examples/sketch/App.js#L36-L44 enjoy 💙

**Comment by mattknappchhj** [comment]
To fix this error, navigate to node_modules/react-native-signature-pad/index.js and make the below changes:

**CHANGE 1**
-------------------------------

import React, { Component, PropTypes } from 'react';
import {
  View,
  WebView,
  StyleSheet,
} from 'react-native';

-- Change to the below --

import React, { Component } from 'react';
import {
  View,
  WebView,
  StyleSheet,
  ViewPropTypes,
} from 'react-native';
import PropTypes from 'prop-types';


**CHANGE 2**
-------------------------------

style: View.propTypes.style,

-- Change to the below --

style: ViewPropTypes.style,


-------------------------------

**Comment by enthal** [comment]
Is this being maintained any more?  The fix is right there in the comment above ("mattknappchhj commented on Feb 1").  In fact there are multiple PRs for this: #27, #28, #30, #31.  @kevinstumpf Thanks!

**Comment by timt** [comment]
Done
