### ISSUE TITLE
Saving data

### ISSUE THREAD

**Issue by talon-i-am** [kevinstumpf/react-native-signature-pad#32]
Instead of having it save to base64 can it save to as JSON data points like so?

```"[{"lx":38,"ly":99,"mx":38,"my":98},{"lx":39,"ly":97,"mx":38,"my":99},{"lx":42,"ly":95,"mx":39,"my":97},{"lx":44,"ly":94,"mx":42,"my":95},{"lx":48,"ly":91,"mx":44,"my":94},{"lx":50,"ly":89,"mx":48,"my":91},{"lx":52,"ly":87,"mx":50,"my":89},{"lx":53,"ly":86,"mx":52,"my":87}]```

**Comment by timt** [comment]
base64 is more a more idomatic way of representing an image.

Will consider adding this as an option if you submit a pull request with the relevant changes.
