### ISSUE TITLE
Ignores size (width/height) often, not always.  In output image.

### ISSUE THREAD

**Issue by enthal** [kevinstumpf/react-native-signature-pad#33]
The pad Ignores size (width/height) sometimes, seemingly randomly.  Sometimes it recognizes the given size in its canvas and underlying output.  More often it chooses for a canvas **a large square** the extends down and right (same origin at upper left).  In this case, one can draw outside the given bounds: clipped in the Pad itself, but visible in the output image.  The output image is then way too big and the wrong proportions.

Makes no difference if size is from parent Component (`flex:1` on the pad's style) or set directly with `width`/`height`.

Has anybody seen this or found a workaround?

This is a deal breaker for me.  :(

**Comment by markhomoki** [comment]
Having the same issue, could you find a solution for this?

**Comment by timt** [comment]
Is this still an issue?

Please provide more detail including:

- Versions of the following:
- react-native
- react-native-signature-pad
- react
- Emulator/Simulator

Code fragment showing your implementation.

**Comment by timt** [comment]
Close due to inactivity
