### ISSUE TITLE
Starting signature on horizontal

### ISSUE THREAD

**Issue by DiegoDevBittencourt** [kevinstumpf/react-native-signature-pad#36]
I just tried on android yet. If I start my trace from left to rigth or vice-versa, it draws a slightly line and stops draw. But if I start from top/bottom or any other direction (45º, 60º etc...) works fine. There's any workaround to this? I really liked this npm, the others that I found doesn't work the "dot" (when user just touch the screen).

Just to let things clear, I can draw horizontal lines, but I need to start from bottom/top or any other direction that is not horizontal itself. Thanks!!

**Comment by timt** [comment]
Is this still an issue?

Please provide more detail including:

- Versions of the following:
- react-native
- react-native-signature-pad
- react
- Emulator/Simulator

Code fragment showing your implementation.

**Comment by timt** [comment]
Close due to inactivity
