### ISSUE TITLE
Super expression must be null or a function error

### ISSUE THREAD

**Issue by giridharkl** [kevinstumpf/react-native-signature-pad#38]
I am getting the following error. Tried all the mentioned methods, no luck, please help!

![screenshot](https://user-images.githubusercontent.com/1477849/51617151-4bae8600-1f34-11e9-8353-fed8171619ef.png)

**Comment by timt** [comment]
Is this still an issue?

Please provide more detail including:

- Versions of the following:
- react-native
- react-native-signature-pad
- react
- Emulator/Simulator

Code fragment showing your implementation.

**Comment by timt** [comment]
Close due to inactivity
