### ISSUE TITLE
react-native-webview needs to be added to yarn.lock

### ISSUE THREAD

**Issue by jedlau** [kevinstumpf/react-native-signature-pad#41]
`react-native-webview` is in `package.json`, but not in `yarn.lock`. As a result, I'm getting the following error: "Module `react-native-webview` does not exist in the Haste module map".

I think this package is missing a "yarn add react-native-webview".

Will it also need a "react-native link react-native-webview", I wonder?

**Comment by timt** [comment]
You need to add react-native-webview to your own package.json, as it is a dependency of this library.

https://github.com/react-native-community/react-native-webview
