### ISSUE TITLE
Provide isEmpty from wrapped component to check for empty canvas/signatures

### ISSUE THREAD

**Issue by j0nd0n7** [kevinstumpf/react-native-signature-pad#42]
The wrapped component has an isEmpty function check for empty canvas. It would be nice to have that in this component.

**Comment by alexandermirzoyan** [comment]
HI @j0nd0n7  ,

 The ref which is created by the component, returns a points array, when it's empty the length of the points is 0.

<SignaturePad
  ref="signature"
  clearButton={true}
/>

const { signature } = this.refs;

console.log(signature); // the output object has a property points[]

or you can pick the value from `signature._isEmpty;`
