### ISSUE TITLE
react-native-signature-pad/index.js`: Module `react-native-webview`

### ISSUE THREAD

**Issue by wamobileapps** [kevinstumpf/react-native-signature-pad#46]
I am getting web-view error with react-native-signature-pad
![Simulator Screen Shot - iPhone Xʀ - 2019-07-11 at 18 52 10](https://user-images.githubusercontent.com/7496724/61054569-54751480-a40d-11e9-9b4a-15bf3e4a2ed8.png)

**Comment by brightsider** [comment]
Just install react-native-webview.
