### ISSUE TITLE
RNCWebView

### ISSUE THREAD

**Issue by arish850** [kevinstumpf/react-native-signature-pad#48]
RNCWebView was not found in the UIManager
![Screenshot_2019-07-26-17-26-12-959_com dorm2](https://user-images.githubusercontent.com/34654686/61950318-1b22d400-afcb-11e9-90c2-ae7115974bef.png)

**Comment by jwellington58** [comment]
I'm having the same problem

**Comment by salomaosnff** [comment]
react-native-webview@5.8.0 worked for me

**Comment by swider** [comment]
There was a breaking change at v7, lock it down to `"react-native-webview": "~6.11.1",`
