### ISSUE TITLE
Unable to use in expo version 35.0.0

### ISSUE THREAD

**Issue by cjinghong** [kevinstumpf/react-native-signature-pad#55]
I'm encountering this error after updating to expo version 35.0.0.

`Unable to resolve module `react-native-webview` from `/Users/chanjinghong/Development/React Native/cjh/node_modules/react-native-signature-pad/index.js`: Module `react-native-webview` does not exist in the Haste module map`

**Comment by guilhermepaula** [comment]
Just install react-native-webview supported by your expo sdk version:

`expo install react-native-webview`
