### ISSUE TITLE
Signature pad taking long time to respond on both iOS and Android

### ISSUE THREAD

**Issue by SAHITYASAI** [kevinstumpf/react-native-signature-pad#57]
Actual Behaviour

I'm navigating to another screen on button press wherein i have a signature-pad implemented using this module. I installed the module as per the module instructions. In **iOS**, sometimes the signature pad is taking **long time to respond** without showing up any errors. And in **Android**, the signature pad is either **blank** sometimes or **taking long time to respond** without showing up any errors. I tried using **setTimeout()** method as suggested in a closed issue but ended up getting an error.

Expected Behaviour

I need to capture signatures on both iOS and Android correctly and send them to previous screen for future use . Can someone help me. Thanks in advance. 

Additional Resource
Heres my code :
`_signaturePadError = (error) => {
        console.error(error);
    };
    _signaturePadChange = ({ base64DataUrl }) => {
        console.log("Got new signature: " + base64DataUrl);
        this.setState({ signature: base64DataUrl });
    };
<SignaturePad
    onError={this._signaturePadError}
    onChange={this._signaturePadChange}
    style={{ flex: 1, backgroundColor: 'white' }}
   />`

**Comment by ocano12** [comment]
Working on Android and can confirm when navigating from another screen the signature pad is blank. When i try to sign it looks like if im trying to scroll instead of signing.

**Comment by waleedarshad** [comment]
@ocano12 facing same issue. How did you resolve it?

**Comment by ocano12** [comment]
@waleedarshad basically had to reset the pad on mount. 

using hooks  i did

`useEffect(() => {
     resetSignature();
}, [])


resetSignature = () => {
        setVisibilty(false)
        setTimout(() => {
            setVisibilty(true)
    }, 0)

`

visibilty is a state with true as the initial state

**Comment by iJimmyWei** [comment]
Fixed the issue on my branch https://github.com/iJimmyWei/react-native-signature-pad/commit/2dde8488b1f6167505fddcab393d5e478d6c0513 if anyone else is having issues with it forcing you to scroll instead of interacting with the signature pad
