### ISSUE TITLE
Rotating cuts the webView

### ISSUE THREAD

**Issue by ocano12** [kevinstumpf/react-native-signature-pad#58]
When you rotate from portrait to landscape the rotation cuts the webview and only the top 1/4 of the signature pad is visible.

Any recommendation on how to resize the actual canvas to fit landscape on rotation?

thanks!

react native .60

  <View style={ styles.base}>
    <SignaturePad
      onError={ props.onError }
      onChange={ props.onChange }
      style={{backgroundColor: 'white', flex:1}}
    />
  </View>;

**Comment by nray621** [comment]
Seeing the same issue. `flex: 1` doesn't seem to be recalculated for the `WebView` sizing on orientation / layout change
