### ISSUE TITLE
Errors when building with react-native v26 or later

### ISSUE THREAD

**Issue by buddingmonkey** [kevinstumpf/react-native-signature-pad#7]
https://github.com/facebook/react-native/releases/tag/v0.25.1

Requiring React API from react-native is now deprecated - 2eafcd4 0b534d1

Instead of:

``` JavaScript
import React, { Component, View } from 'react-native';
```

you should now:

``` JavaScript
import React, { Component } from 'react';
import { View } from 'react-native';  
```

Potential fix with pull-request #6

**Comment by kevinstumpf** [comment]
Merged PR! Thank you!
