### ISSUE TITLE
How do I get the exported PNG files to have a transparent background

### ISSUE THREAD

**Issue by davidasconsulting** [kevinstumpf/react-native-signature-pad#73]
Love your library.  Works like a charm.  

Is there a way to get the resulting PNG files to have black writing on a transparent background?  

Can I just set the exportBackgroundColor prop to 'transparent'

**Comment by waaplog** [comment]
use transparent color codes.
      #FFFFFF00

<SignaturePad
        onError={_signaturePadError}
        onChange={_signaturePadChange}
        style={{flex: 1, backgroundColor: '#FFFFFF00'}}
      />

**Comment by davidasconsulting** [comment]
Thank you
